### ISSUE TITLE
Could not connect to sync server

### ISSUE THREAD

**Issue by casainho** [streetwriters/notesnook-sync-server#13]
Thanks for the great notes app. I am using Joplin but I am now looking at notesnook because It have better tables, collapsible blocks of text and a web app other than the PC and mobile apps. 

I am using v1.0-beta.1 on a PC Linux Ubuntu server.

I started to run all this on the PC server, and using localhost, the webapp as also the Linux app, could sync the notes, etc. Then I moved to my public hostname and I got health test working:

http://mydomain.duckdns.org:5264/health shows healthy on the browser. But I get this error on the app:

![image](https://github.com/user-attachments/assets/2ce22c7a-0308-409e-a15a-566fe7442bc9)

```[tasklist]
### Tasks
```

**Comment by thecodrr** [comment]
It's http. You need HTTPS.

**Comment by casainho** [comment]
Thanks!

I must say meanwhile I found I can't share notebooks, that is a big no to me, as currently I share a big "family" notebook with my wife, on Joplin. So, I will check again NotesNook in next months.
