### ISSUE TITLE
I noticed that the self-hosted server has not been released yet, maybe selling self-hosted lifetime licenses will make the team more motivated.

### ISSUE THREAD

**Issue by Littleweisheit** [streetwriters/notesnook-sync-server#2]
Of course, people would definitely be more willing to accept completely free self-hosting, but self-hosting has not appeared for a long time. _Does it conflict with business operations?_ Self-hosting of standard notes is a subscription system, which is difficult for me to accept. I hope there is free or lifetime license self-hosting.

**Comment by thecodrr** [comment]
There's no need to open a new issue. You can follow the conversation at #1 and leave your comments there.
