### ISSUE TITLE
S3 external url protocol only http?

### ISSUE THREAD

**Issue by dyw770** [streetwriters/notesnook-sync-server#6]
https://github.com/streetwriters/notesnook-sync-server/blob/b12eb39797c1effcef4e5d4e2f5be0d9a8dc7cf2/Notesnook.API/Services/S3Service.cs#L232

This part of the code restricts the S3 protocol to only HTTP. When I modify the SELF_HOSTED environment variable, it will cause other problems. delete the `Protocol = Constants.IS_SELF_HOSTED ? Protocol.HTTP : Protocol.HTTPS,` use the protocol in `S3_SRVICE_URL` instead?

**Comment by thecodrr** [comment]
Using an external S3 provider is not supported. The sync server uses self hosted Minio by default which runs as part of the `docker-compose.yml`.

**Comment by dyw770** [comment]
Does this project accept `pull requests`? I would like to submit a `pull request` when I discover any issues in the future

**Comment by thecodrr** [comment]
@dyw770 sure!
